# fly.toml app configuration file generated for cross-detection on 2023-05-01T18:56:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ped4you-cross-detection"
primary_region = "sin"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
